# Generated by Django 2.2.4 on 2019-11-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portafolio',
            options={'permissions': (('profesor', 'Es profesor'), ('alumno', 'Es alumno'))},
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='fecha_crea',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='fecha_publ',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
