# Generated by Django 2.0.9 on 2018-10-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0002_auto_20181025_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
