# Generated by Django 2.0.9 on 2018-10-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0003_auto_20181026_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.TextField(max_length=200),
        ),
    ]
