# Generated by Django 2.0.9 on 2018-10-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0006_dueño'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('run', models.TextField(max_length=9)),
                ('nombre', models.TextField(max_length=60)),
                ('apellido', models.TextField(max_length=60)),
                ('fechanacimiento', models.TextField(max_length=60)),
                ('telefono', models.IntegerField()),
                ('region', models.TextField(max_length=100)),
                ('ciudad', models.TextField(max_length=100)),
                ('tipo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.TextField(max_length=60)),
                ('raza', models.TextField(max_length=60)),
                ('descripcion', models.TextField(max_length=100)),
                ('estadomascota', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=60)),
                ('contraseña', models.TextField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Dueño',
        ),
    ]
