# Generated by Django 2.0.9 on 2018-10-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0008_auto_20181028_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
