# Generated by Django 2.0.9 on 2018-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0009_auto_20181028_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=60)),
                ('foto', models.FileField(blank=True, null=True, upload_to='')),
                ('nombre', models.TextField(max_length=60)),
                ('raza', models.TextField(max_length=60)),
                ('descripcion', models.TextField(max_length=100)),
                ('estadomascota', models.TextField(max_length=100)),
            ],
        ),
    ]
