# Generated by Django 2.0.9 on 2018-10-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0010_perros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perros',
            old_name='estadomascota',
            new_name='estado',
        ),
    ]
