# Generated by Django 2.0.9 on 2018-10-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0011_auto_20181029_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perros',
            name='codigo',
            field=models.TextField(max_length=100),
        ),
    ]
