# Generated by Django 2.0.9 on 2018-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0012_auto_20181029_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('contraseña', models.TextField(max_length=30)),
                ('descripcion', models.TextField(max_length=2)),
            ],
        ),
    ]
