# Generated by Django 2.0.9 on 2018-10-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0013_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='apellido',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='nombre',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contraseña',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=2),
        ),
    ]
