# Generated by Django 2.0.9 on 2018-10-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0014_auto_20181029_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contraseña',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
