# Generated by Django 2.0.9 on 2018-10-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0016_auto_20181029_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='run',
            field=models.TextField(max_length=13),
        ),
    ]
