# Generated by Django 2.0.9 on 2018-11-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0017_auto_20181031_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
    ]
