# Generated by Django 3.0 on 2019-12-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misperris', '0018_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
